### ISSUE TITLE
Some URLs that should match don't due to different stored hashes

### ISSUE THREAD

**Issue by igmoweb** [humanmade/hm-redirects#44] opened 2020-11-17 15:21 UTC
These URLs:

- https://site.local/should-redirect/
- https://site.local/should-redirect

Are essentially the same URL. However, hm-redirects don't take the trailing slash into account. When parsing the URL, I think that the plugin should normalize the URLs before storing them into database and generate their hashes.

It also happens if the lead slash is not present in the relative path when a new redirect is created. It also needs to be normalized in some way.

Note that if a URL contains a slash in any of its query args, this normalization should not affect those args.

**Comment by roborourke** [comment] 2022-01-10 11:27
Duplicate of #34

**Closed by roborourke** 2022-01-10 11:27 UTC
Labels: bug, enhancement
